version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: uta_security_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TuPasswordSeguro123!
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d # Opcional: para scripts iniciales